#!/bin/bash
# 
#Script for invoking CMake using the above CMakeLists.txt.  Invoke
# this script in the source directory containing CMakeLists.txt:
#
# $ ./do-configure
# $ make
#
# You will need to change the TRILINOS_PATH variable below to point to
# the location of your Trilinos install.  Other variables that you may
# need or want to change:
#
# CMAKE_BUILD_TYPE: "DEBUG" or "RELEASE".
#
# BUILD_SHARED_LIBS: If your build of Trilinos includes shared /
# dynamic libraries, you can save build time by linking against them
# instead of static libraries.  Otherwise, set this to OFF.
#
# CMAKE_VERBOSE_MAKEFILE: Set to ON if you prefer verbose Make output.
#

rm -rf CMake*

cmake \
  -Wno-dev \
  -D ALIPT_BUILD_PMCPU:BOOL=ON \
  -D TRILINOS_DIR:FILEPATH=/global/cfs/cdirs/fanssie/automated_testing/weeklyCDashPerlmutter/serial/builds/TrilinosInstall \
  -D SFAD12_EXE_DIR:FILEPATH=/global/cfs/cdirs/fanssie/automated_testing/weeklyCDashPerlmutter/serial/builds/AlbanyInstallSfad12/bin \
  -D SFAD24_EXE_DIR:FILEPATH=/global/cfs/cdirs/fanssie/automated_testing/weeklyCDashPerlmutter/serial/builds/AlbanyInstallSfad24/bin \
  -D MALI_EXE_DIR:FILEPATH=/global/cfs/cdirs/fanssie/automated_testing/weeklyCDashPerlmutter/serial/builds/mali \
  -D MESH_FILE_DIR:FILEPATH=/global/cfs/cdirs/fanssie/automated_testing/ali-perf-tests-meshes \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
/global/homes/j/jwatkins/LandIce/ali-perf-tests
