#!/bin/bash
# 
# Script for invoking CMake using the above CMakeLists.txt.  Invoke
# this script in the source directory containing CMakeLists.txt:
#
# $ ./do-configure
# $ make
#
# You will need to change the TRILINOS_PATH variable below to point to
# the location of your Trilinos install.  Other variables that you may
# need or want to change:
#
# CMAKE_BUILD_TYPE: "DEBUG" or "RELEASE".
#
# BUILD_SHARED_LIBS: If your build of Trilinos includes shared /
# dynamic libraries, you can save build time by linking against them
# instead of static libraries.  Otherwise, set this to OFF.
#
# CMAKE_VERBOSE_MAKEFILE: Set to ON if you prefer verbose Make output.
#

CMAKE_PATH=../tpls/cmake/3.20.0/gnu
rm -rf CMake*

${CMAKE_PATH}/bin/cmake \
  -Wno-dev \
  -D ALIPT_BUILD_ICME_CPU:BOOL=ON \
  -D TRILINOS_DIR:FILEPATH= \
  -D SFAD6_EXE_DIR:FILEPATH= \
  -D SFAD12_EXE_DIR:FILEPATH= \
  -D MESH_FILE_DIR:FILEPATH=../meshes \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
../
